-- MariaDB-flavored equivalent of db/migration/postgresql/V1__init.sql.
-- Kept schema-identical (same tables/columns/constraints); only the dialect syntax differs
-- (AUTO_INCREMENT instead of GENERATED BY DEFAULT AS IDENTITY, TEXT instead of CLOB,
-- explicit table-level FOREIGN KEY clauses, InnoDB engine).

CREATE TABLE app_users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
) ENGINE=InnoDB;

CREATE TABLE app_user_roles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role VARCHAR(64) NOT NULL,
    UNIQUE KEY uq_app_user_roles (user_id, role),
    CONSTRAINT fk_app_user_roles_user FOREIGN KEY (user_id) REFERENCES app_users(id)
) ENGINE=InnoDB;

CREATE TABLE agents (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(2000),
    owner VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    environment VARCHAR(64),
    api_key_hash VARCHAR(255),
    allowed_tool_groups VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
) ENGINE=InnoDB;

CREATE TABLE tools (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(64) NOT NULL,
    tool_group VARCHAR(128) NOT NULL DEFAULT 'default',
    endpoint_url VARCHAR(1024),
    owner VARCHAR(255),
    environment VARCHAR(64),
    description VARCHAR(4000),
    schema_json LONGTEXT,
    approved_hash VARCHAR(128),
    current_hash VARCHAR(128),
    approval_status VARCHAR(32) NOT NULL,
    last_seen_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
) ENGINE=InnoDB;

CREATE TABLE tool_versions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tool_id BIGINT NOT NULL,
    schema_json LONGTEXT,
    description VARCHAR(4000),
    hash VARCHAR(128) NOT NULL,
    detected_at TIMESTAMP NOT NULL,
    approved_by VARCHAR(255),
    approved_at TIMESTAMP NULL,
    status VARCHAR(32) NOT NULL,
    CONSTRAINT fk_tool_versions_tool FOREIGN KEY (tool_id) REFERENCES tools(id)
) ENGINE=InnoDB;

CREATE INDEX idx_tool_versions_tool_id ON tool_versions(tool_id);

CREATE TABLE gateway_requests (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    correlation_id VARCHAR(64) NOT NULL UNIQUE,
    user_id VARCHAR(255),
    agent_id BIGINT NOT NULL,
    tool_id BIGINT,
    action_name VARCHAR(255) NOT NULL,
    action_category VARCHAR(32) NOT NULL,
    target_environment VARCHAR(64),
    request_body_hash VARCHAR(128),
    request_summary VARCHAR(4000),
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_gateway_requests_agent FOREIGN KEY (agent_id) REFERENCES agents(id),
    CONSTRAINT fk_gateway_requests_tool FOREIGN KEY (tool_id) REFERENCES tools(id)
) ENGINE=InnoDB;

CREATE INDEX idx_gateway_requests_agent_id ON gateway_requests(agent_id);
CREATE INDEX idx_gateway_requests_tool_id ON gateway_requests(tool_id);
CREATE INDEX idx_gateway_requests_created_at ON gateway_requests(created_at);

CREATE TABLE policy_decisions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    gateway_request_id BIGINT NOT NULL,
    decision VARCHAR(32) NOT NULL,
    policy_version VARCHAR(64),
    reason VARCHAR(4000),
    risk_score INT NOT NULL,
    risk_level VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_policy_decisions_request FOREIGN KEY (gateway_request_id) REFERENCES gateway_requests(id)
) ENGINE=InnoDB;

CREATE INDEX idx_policy_decisions_request_id ON policy_decisions(gateway_request_id);

CREATE TABLE approval_requests (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    gateway_request_id BIGINT NOT NULL,
    requested_by VARCHAR(255),
    assigned_to VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    reason VARCHAR(4000),
    approved_by VARCHAR(255),
    approved_at TIMESTAMP NULL,
    rejected_by VARCHAR(255),
    rejected_at TIMESTAMP NULL,
    expires_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_approval_requests_request FOREIGN KEY (gateway_request_id) REFERENCES gateway_requests(id)
) ENGINE=InnoDB;

CREATE INDEX idx_approval_requests_status ON approval_requests(status);
CREATE INDEX idx_approval_requests_request_id ON approval_requests(gateway_request_id);

CREATE TABLE audit_events (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    correlation_id VARCHAR(64),
    event_type VARCHAR(64) NOT NULL,
    actor_type VARCHAR(32) NOT NULL,
    actor_id VARCHAR(255),
    agent_id BIGINT,
    tool_id BIGINT,
    severity VARCHAR(32) NOT NULL,
    message VARCHAR(4000) NOT NULL,
    metadata_json LONGTEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_audit_events_agent FOREIGN KEY (agent_id) REFERENCES agents(id),
    CONSTRAINT fk_audit_events_tool FOREIGN KEY (tool_id) REFERENCES tools(id)
) ENGINE=InnoDB;

CREATE INDEX idx_audit_events_correlation_id ON audit_events(correlation_id);
CREATE INDEX idx_audit_events_created_at ON audit_events(created_at);
CREATE INDEX idx_audit_events_severity ON audit_events(severity);

CREATE TABLE incidents (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    related_audit_event_id BIGINT,
    related_gateway_request_id BIGINT,
    summary VARCHAR(4000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_incidents_audit_event FOREIGN KEY (related_audit_event_id) REFERENCES audit_events(id),
    CONSTRAINT fk_incidents_gateway_request FOREIGN KEY (related_gateway_request_id) REFERENCES gateway_requests(id)
) ENGINE=InnoDB;

CREATE INDEX idx_incidents_status ON incidents(status);

CREATE TABLE policies (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    version INT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    mode VARCHAR(32) NOT NULL,
    rule_json LONGTEXT,
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    UNIQUE KEY uq_policies_name_version (name, version)
) ENGINE=InnoDB;
