-- MCP authorization/consent model (design-mcp-authorization.md): per-agent, per-MCP-server
-- consent grants (the confused-deputy fix) plus OAuth 2.1 client_credentials support for MCP
-- servers that require it. Entirely additive: auth_mode defaults to 'NONE', matching today's
-- only behavior — no existing MCP tool call is affected until an operator explicitly grants at
-- least one mcp_consents row, which every MCP-backed gateway call now requires regardless of
-- auth_mode (improvement_plan.md P1, "MCP Authorization And Confused-Deputy Controls Are
-- Missing").
ALTER TABLE mcp_servers ADD COLUMN auth_mode VARCHAR(32) NOT NULL DEFAULT 'NONE';
ALTER TABLE mcp_servers ADD COLUMN oauth_issuer VARCHAR(1024);
ALTER TABLE mcp_servers ADD COLUMN oauth_resource VARCHAR(1024);
ALTER TABLE mcp_servers ADD COLUMN oauth_token_endpoint VARCHAR(1024);
ALTER TABLE mcp_servers ADD COLUMN oauth_client_id VARCHAR(512);
ALTER TABLE mcp_servers ADD COLUMN oauth_client_secret_ref VARCHAR(512);
ALTER TABLE mcp_servers ADD COLUMN oauth_scopes VARCHAR(1024);

CREATE TABLE mcp_consents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL REFERENCES agents(id),
    mcp_server_id BIGINT NOT NULL REFERENCES mcp_servers(id),
    tool_name VARCHAR(255),
    action_category VARCHAR(32),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    granted_by VARCHAR(255) NOT NULL,
    granted_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP,
    revoked_by VARCHAR(255),
    revoked_at TIMESTAMP
);

CREATE INDEX idx_mcp_consents_agent_server ON mcp_consents(agent_id, mcp_server_id);

-- Cached OAuth access token per MCP server, AES-256-GCM encrypted with
-- agentshield.mcp.oauth-token-encryption-key. Never exposed via any API/log/audit event.
CREATE TABLE mcp_oauth_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcp_server_id BIGINT NOT NULL UNIQUE REFERENCES mcp_servers(id),
    access_token_encrypted TEXT NOT NULL,
    issued_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    scope VARCHAR(1024)
);
