-- Tool/skill supply-chain provenance (design-tool-supply-chain-provenance.md, improvement_plan.md
-- P1 "Tool/Skill Supply-Chain Provenance Is Not Strong Enough"). Entirely additive: every
-- existing tool defaults to source_type='CUSTOM_HTTP' (or 'MCP' backfilled below), and every
-- ToolVersion without a tool_provenance row is implicitly UNVERIFIED — nothing currently
-- approved is affected until an operator opts a source type into
-- agentshield.provenance.require-signature-for.
ALTER TABLE tools ADD COLUMN source_type VARCHAR(32) NOT NULL DEFAULT 'CUSTOM_HTTP';
UPDATE tools SET source_type = 'MCP' WHERE mcp_server_id IS NOT NULL;
UPDATE tools SET source_type = 'BUILT_IN' WHERE name IN ('mock-git', 'mock-database', 'mock-filesystem', 'mock-saas-crm');

CREATE TABLE tool_provenance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_version_id BIGINT NOT NULL UNIQUE REFERENCES tool_versions(id),
    publisher VARCHAR(512),
    checksum_algorithm VARCHAR(32),
    checksum VARCHAR(128),
    verification_mode VARCHAR(32) NOT NULL DEFAULT 'UNVERIFIED',
    signature_bundle TEXT,
    certificate_identity VARCHAR(1024),
    certificate_issuer VARCHAR(1024),
    public_key_ref VARCHAR(512),
    verified_at TIMESTAMP,
    verified_by VARCHAR(255),
    verification_details VARCHAR(2000)
);

CREATE INDEX idx_tool_provenance_tool_version ON tool_provenance(tool_version_id);
