-- Database-backed DLP rules (improvement_plan.md A2), mirroring policy_overrides (V6): which
-- built-in detectors run and what happens on a match is configured here, not in code. When no
-- enabled profile exists, DlpScanService falls back to a safe built-in default (all detectors on,
-- BLOCK on any match) so DLP protection is active immediately after this migration.
CREATE TABLE classification_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    locale VARCHAR(16),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    detect_secrets BOOLEAN NOT NULL DEFAULT TRUE,
    detect_pii BOOLEAN NOT NULL DEFAULT TRUE,
    detect_prompt_injection BOOLEAN NOT NULL DEFAULT TRUE,
    -- JSON array of operator-supplied regex strings, matched as DetectorCategory.CUSTOM_PATTERN.
    custom_patterns_json TEXT,
    default_action VARCHAR(32) NOT NULL DEFAULT 'BLOCK',
    priority INT NOT NULL DEFAULT 100,
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_classification_profiles_enabled ON classification_profiles(enabled);
