-- DLP detector hits (improvement_plan.md A2), recorded the same way gateway_tool_responses (V8)
-- already does for response scanning: indicator name, category, confidence, and location only —
-- never the matched substring itself. correlation_id reuses the gateway's existing trace-id
-- concept (gateway_requests.correlation_id) rather than a separate identifier, but is not a hard
-- FK since a DLP scan can also happen outside a gateway request (e.g. the RAG chunk scan endpoint).
CREATE TABLE dlp_findings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correlation_id VARCHAR(64),
    content_stage VARCHAR(32) NOT NULL,
    indicator VARCHAR(128) NOT NULL,
    category VARCHAR(32) NOT NULL,
    confidence VARCHAR(16) NOT NULL,
    match_offset INT,
    match_length INT,
    action_taken VARCHAR(32) NOT NULL,
    classification_profile_id BIGINT,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_dlp_findings_correlation_id ON dlp_findings(correlation_id);
CREATE INDEX idx_dlp_findings_content_stage ON dlp_findings(content_stage);
CREATE INDEX idx_dlp_findings_category ON dlp_findings(category);
CREATE INDEX idx_dlp_findings_created_at ON dlp_findings(created_at);
