-- Reversible DLP tokenization records (improvement_plan.md A2). Only ever populated when
-- agentshield.dlp.enable-reversible-tokenization=true (off by default) — otherwise RedactionService
-- issues an irreversible "[REDACTED:CATEGORY]" placeholder and no row is written here at all.
CREATE TABLE redaction_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(64) NOT NULL UNIQUE,
    category VARCHAR(32) NOT NULL,
    -- AES-GCM ciphertext, base64, encrypted with agentshield.dlp.tokenization-encryption-key.
    encrypted_original TEXT NOT NULL,
    expires_at TIMESTAMP,
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_redaction_tokens_token ON redaction_tokens(token);
