-- Records each run of AttackSimulatorService (improvement_plan.md A5) so the coverage dashboard
-- can show "last validated" per scenario, not just "last fired in production traffic".
CREATE TABLE detection_validation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_code VARCHAR(64) NOT NULL,
    detection_rule_code VARCHAR(64),
    passed BOOLEAN NOT NULL,
    detail VARCHAR(2000),
    triggered_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_detection_validation_runs_scenario ON detection_validation_runs(scenario_code);
CREATE INDEX idx_detection_validation_runs_rule ON detection_validation_runs(detection_rule_code);
