-- AI Coding Assistant Risk Manager (improvement_plan.md A4): submitted scan results are evaluated
-- into PASSED/BLOCKED, a BLOCKED assessment is reviewed directly on this entity (approved_by/
-- rejected_by columns) rather than through approval_requests — that table mandatorily references
-- a gateway_requests row and its approve() executes a tool call, neither of which applies to
-- reviewing a code assessment. A PASSED assessment gets exactly one signed receipt.
CREATE TABLE code_assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo VARCHAR(512) NOT NULL,
    commit_sha VARCHAR(64) NOT NULL,
    branch VARCHAR(255),
    author VARCHAR(255),
    source VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    requires_rescan BOOLEAN NOT NULL DEFAULT FALSE,
    requested_by VARCHAR(255),
    approved_by VARCHAR(255),
    approved_at TIMESTAMP,
    rejected_by VARCHAR(255),
    rejected_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_code_assessments_repo_branch ON code_assessments(repo, branch);
CREATE INDEX idx_code_assessments_status ON code_assessments(status);

CREATE TABLE code_findings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES code_assessments(id),
    file_path VARCHAR(1024),
    line INT,
    category VARCHAR(32) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    rule_id VARCHAR(128),
    message VARCHAR(2000),
    status VARCHAR(16) NOT NULL DEFAULT 'OPEN'
);

CREATE INDEX idx_code_findings_assessment_id ON code_findings(assessment_id);

-- One receipt per PASSED assessment; commit_sha/scan_summary_hash are the exact bytes the
-- Ed25519 signature covers (ReceiptSigningService), so a receipt is verifiable from these two
-- columns plus the signature alone, without trusting any other row in this table.
CREATE TABLE ai_code_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL UNIQUE REFERENCES code_assessments(id),
    commit_sha VARCHAR(64) NOT NULL,
    sbom_hash VARCHAR(128),
    scan_summary_hash VARCHAR(128) NOT NULL,
    algorithm VARCHAR(32) NOT NULL,
    signature VARCHAR(512) NOT NULL,
    signer_key_id VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
