-- SOC Validation Module (improvement_plan.md N1, folded into AgentShield rather than a separate
-- product). Adds:
--   1. A nullable MITRE ATT&CK reference on the existing detection_rules catalog, alongside the
--      OWASP-style category it already carries.
--   2. Two new detection_rules entries for subsystems that already fire today but weren't yet
--      cataloged: MCP OAuth token rejection (com.agentshield.mcp.McpOAuthTokenService, existing
--      since the MCP authorization work) and the new AI-coding-assistant block rule (Phase 3,
--      com.agentshield.codetrust.CodeAssessmentService).
--   3. validation_run: records an external alert-import validation (distinct from
--      detection_validation_runs, which records AttackSimulatorService's own in-process scenario
--      replays — this table is for checking a downstream SIEM/alerting tool's *actual* alert
--      export against an expected-detections manifest).
--
-- MITRE mapping notes: a mapping is only added where the rule detects a pattern that corresponds
-- to a real attacker technique. Rules left NULL are either (a) behavioral-anomaly detection
-- methods (first_seen_combination, repeated_denials, unusual_approval_frequency, volume_spike) —
-- ATT&CK catalogs attacker TTPs, not detection methods, so there is no technique to reference —
-- or (b) deny-tool-outside-allowed-group, where no single classic ATT&CK technique cleanly fits
-- an agent-authorization-scope violation. Forcing a mapping in either case would be a weak,
-- invented reference, not a defensible one.
ALTER TABLE detection_rules ADD COLUMN mitre_attack_id VARCHAR(32);

UPDATE detection_rules SET mitre_attack_id = 'T1195' WHERE code = 'deny-schema-drift';
UPDATE detection_rules SET mitre_attack_id = 'T1485' WHERE code = 'deny-prod-destructive-without-approval';
UPDATE detection_rules SET mitre_attack_id = 'T1552' WHERE code = 'deny-secret-external-transfer';
UPDATE detection_rules SET mitre_attack_id = 'ATLAS:AML.T0051' WHERE code = 'deny-prompt-injection-response';
UPDATE detection_rules SET mitre_attack_id = 'T1078' WHERE code = 'deny-disabled-agent';
UPDATE detection_rules SET mitre_attack_id = 'T1567' WHERE code = 'require-approval-external-transfer';
UPDATE detection_rules SET mitre_attack_id = 'T1552' WHERE code = 'deny-dlp-block';
UPDATE detection_rules SET mitre_attack_id = 'T1552' WHERE code = 'require-approval-dlp-finding';

INSERT INTO detection_rules (code, name, category, description, source, reference_id, mitre_attack_id, created_at) VALUES
('mcp-oauth-token-rejected', 'MCP OAuth token rejected (wrong audience/issuer/expired/scope)', 'IDENTITY_PRIVILEGE_ABUSE', 'An OAuth 2.1 access token for an MCP server failed audience, issuer, expiry, or scope validation and was discarded, never cached.', 'MCP_OAUTH', 'mcp.oauth_token_rejected', 'T1528', CURRENT_TIMESTAMP),
('codetrust-blocked', 'AI-assisted code assessment blocked on a HIGH/CRITICAL finding', 'SUPPLY_CHAIN_RISK', 'A submitted code assessment (CLI/CI scan result) contained a HIGH or CRITICAL finding (e.g. a committed secret) and was blocked pending human review.', 'CODE_TRUST', 'codetrust.blocked', 'T1195.001', CURRENT_TIMESTAMP);

CREATE TABLE validation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    triggered_by VARCHAR(255),
    matched_count INT NOT NULL,
    missed_count INT NOT NULL,
    unexpected_count INT NOT NULL,
    matched_scenarios_json VARCHAR(4000),
    missed_scenarios_json VARCHAR(4000),
    unexpected_alerts_json VARCHAR(4000),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_validation_runs_created_at ON validation_runs(created_at);
