-- Portable DDL: must run unchanged on H2 (test profile, MODE=PostgreSQL) and PostgreSQL.

CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE app_user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    role VARCHAR(64) NOT NULL,
    UNIQUE (user_id, role)
);

CREATE TABLE agents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(2000),
    owner VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    environment VARCHAR(64),
    api_key_hash VARCHAR(255),
    allowed_tool_groups VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(64) NOT NULL,
    tool_group VARCHAR(128) NOT NULL DEFAULT 'default',
    endpoint_url VARCHAR(1024),
    owner VARCHAR(255),
    environment VARCHAR(64),
    description VARCHAR(4000),
    schema_json TEXT,
    approved_hash VARCHAR(128),
    current_hash VARCHAR(128),
    approval_status VARCHAR(32) NOT NULL,
    last_seen_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE tool_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_id BIGINT NOT NULL REFERENCES tools(id),
    schema_json TEXT,
    description VARCHAR(4000),
    hash VARCHAR(128) NOT NULL,
    detected_at TIMESTAMP NOT NULL,
    approved_by VARCHAR(255),
    approved_at TIMESTAMP,
    status VARCHAR(32) NOT NULL
);

CREATE INDEX idx_tool_versions_tool_id ON tool_versions(tool_id);

CREATE TABLE gateway_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correlation_id VARCHAR(64) NOT NULL UNIQUE,
    user_id VARCHAR(255),
    agent_id BIGINT NOT NULL REFERENCES agents(id),
    tool_id BIGINT REFERENCES tools(id),
    action_name VARCHAR(255) NOT NULL,
    action_category VARCHAR(32) NOT NULL,
    target_environment VARCHAR(64),
    request_body_hash VARCHAR(128),
    request_summary VARCHAR(4000),
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_gateway_requests_agent_id ON gateway_requests(agent_id);
CREATE INDEX idx_gateway_requests_tool_id ON gateway_requests(tool_id);
CREATE INDEX idx_gateway_requests_created_at ON gateway_requests(created_at);

CREATE TABLE policy_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gateway_request_id BIGINT NOT NULL REFERENCES gateway_requests(id),
    decision VARCHAR(32) NOT NULL,
    policy_version VARCHAR(64),
    reason VARCHAR(4000),
    risk_score INT NOT NULL,
    risk_level VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_policy_decisions_request_id ON policy_decisions(gateway_request_id);

CREATE TABLE approval_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gateway_request_id BIGINT NOT NULL REFERENCES gateway_requests(id),
    requested_by VARCHAR(255),
    assigned_to VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    reason VARCHAR(4000),
    approved_by VARCHAR(255),
    approved_at TIMESTAMP,
    rejected_by VARCHAR(255),
    rejected_at TIMESTAMP,
    expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_approval_requests_status ON approval_requests(status);
CREATE INDEX idx_approval_requests_request_id ON approval_requests(gateway_request_id);

CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correlation_id VARCHAR(64),
    event_type VARCHAR(64) NOT NULL,
    actor_type VARCHAR(32) NOT NULL,
    actor_id VARCHAR(255),
    agent_id BIGINT REFERENCES agents(id),
    tool_id BIGINT REFERENCES tools(id),
    severity VARCHAR(32) NOT NULL,
    message VARCHAR(4000) NOT NULL,
    metadata_json TEXT,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_audit_events_correlation_id ON audit_events(correlation_id);
CREATE INDEX idx_audit_events_created_at ON audit_events(created_at);
CREATE INDEX idx_audit_events_severity ON audit_events(severity);

CREATE TABLE incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    related_audit_event_id BIGINT REFERENCES audit_events(id),
    related_gateway_request_id BIGINT REFERENCES gateway_requests(id),
    summary VARCHAR(4000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_incidents_status ON incidents(status);

CREATE TABLE policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    version INT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    mode VARCHAR(32) NOT NULL,
    rule_json TEXT,
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    UNIQUE (name, version)
);
