-- Explicit Entitlements release, work package 2 (agentshield_policy_evidence_execution_plan
-- section 7). Entirely additive/new table — no existing schema changes. Governed at evaluation
-- time by agentshield.grants.transition-mode, which defaults to GROUPS_ONLY: this table having
-- zero rows changes nothing about today's behavior for any existing installation.
CREATE TABLE agent_tool_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL REFERENCES agents(id),
    tool_id BIGINT NOT NULL REFERENCES tools(id),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    action_category VARCHAR(32),
    target_environment VARCHAR(64),
    resource_path_pattern VARCHAR(512),
    required_token_scope VARCHAR(256),
    not_before TIMESTAMP,
    expires_at TIMESTAMP,
    created_by VARCHAR(255),
    revoked_by VARCHAR(255),
    revoked_at TIMESTAMP,
    reason VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_agent_tool_grants_lookup ON agent_tool_grants(agent_id, tool_id, status);
