-- Explicit Entitlements release, work package 3 (agentshield_policy_evidence_execution_plan
-- section 8). Entirely additive. approval_requests.assigned_to is untouched (legacy field,
-- preserved for compatibility) — approval_profile_id/assigned_role are new, separate columns.
CREATE TABLE approval_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    priority INT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(2000),
    agent_id BIGINT REFERENCES agents(id),
    tool_id BIGINT REFERENCES tools(id),
    tool_group VARCHAR(128),
    action_category VARCHAR(32),
    target_environment VARCHAR(64),
    risk_tier VARCHAR(32),
    target_role VARCHAR(32) NOT NULL,
    expiration_minutes INT,
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_approval_profiles_priority ON approval_profiles(priority);

ALTER TABLE approval_requests ADD COLUMN approval_profile_id BIGINT REFERENCES approval_profiles(id);
ALTER TABLE approval_requests ADD COLUMN assigned_role VARCHAR(32);
