-- Replaces the single agents.api_key_hash field with a full credential lifecycle: multiple
-- tokens per agent over time, each individually revocable/expirable, with last-used tracking
-- (improvement_plan.md #3). Plaintext tokens are never stored — only their SHA-256 hash, plus
-- a short prefix so an operator can recognize a credential in the UI without seeing the token.

CREATE TABLE agent_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL REFERENCES agents(id),
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    token_prefix VARCHAR(16) NOT NULL,
    status VARCHAR(32) NOT NULL,
    expires_at TIMESTAMP,
    last_used_at TIMESTAMP,
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    revoked_by VARCHAR(255),
    revoked_at TIMESTAMP
);

CREATE INDEX idx_agent_credentials_agent_id ON agent_credentials(agent_id);
CREATE INDEX idx_agent_credentials_status ON agent_credentials(status);

ALTER TABLE agents DROP COLUMN api_key_hash;
