-- Database-backed policy overrides (improvement_plan.md #8). The fixed Java rules in
-- PolicyEngine remain the safety-net baseline and always run first; an override only takes
-- effect when the baseline would otherwise ALLOW, so an override can add extra restriction (or,
-- for an ADMIN who explicitly wants it, a scoped extra allowance) without weakening the baseline.
CREATE TABLE policy_overrides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    action_category VARCHAR(32),
    target_environment VARCHAR(64),
    tool_group VARCHAR(128),
    agent_name VARCHAR(255),
    decision VARCHAR(32) NOT NULL,
    reason VARCHAR(2000) NOT NULL,
    priority INT NOT NULL DEFAULT 100,
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_policy_overrides_enabled ON policy_overrides(enabled);
