-- MCP (Model Context Protocol) server registry (improvement_plan.md #6). Discovered tools from
-- an MCP server become regular rows in the existing `tools` table (linked back via
-- mcp_server_id/mcp_tool_name) so they flow through the exact same policy/risk/audit pipeline
-- as any other tool — no changes needed to the gateway itself.
CREATE TABLE mcp_servers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    transport_type VARCHAR(32) NOT NULL,
    endpoint_url VARCHAR(1024),
    command VARCHAR(1024),
    args VARCHAR(2000),
    env_ref VARCHAR(255),
    owner VARCHAR(255),
    environment VARCHAR(64),
    tool_group VARCHAR(128) NOT NULL DEFAULT 'default',
    discovered_tools_hash VARCHAR(128),
    last_discovered_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

ALTER TABLE tools ADD COLUMN mcp_server_id BIGINT REFERENCES mcp_servers(id);
ALTER TABLE tools ADD COLUMN mcp_tool_name VARCHAR(255);
