-- Forensic record of what a tool actually returned, without storing the raw response by
-- default (improvement_plan.md #7). response_summary is a sanitized preview: full text for a
-- clean/ALLOWed response (the agent already received it), or just the matched detector
-- indicator names — never the raw matched text — for a blocked one. detector_matches_json lists
-- indicator names only (SecretDetector/PromptInjectionDetector never return the matched
-- substring itself, only a pattern name like "aws-access-key").
CREATE TABLE gateway_tool_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gateway_request_id BIGINT NOT NULL REFERENCES gateway_requests(id),
    status_code INT,
    response_body_hash VARCHAR(128),
    response_summary VARCHAR(4000),
    blocked BOOLEAN NOT NULL DEFAULT FALSE,
    block_reason VARCHAR(2000),
    detector_matches_json VARCHAR(2000),
    -- Only populated when agentshield.audit.retain-raw-tool-responses=true, AES-GCM encrypted
    -- with agentshield.audit.raw-response-encryption-key. Off by default.
    raw_response_encrypted TEXT,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_gateway_tool_responses_request_id ON gateway_tool_responses(gateway_request_id);
